//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_AlquilerEquipos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlquilerDetalle
    {
        public int Id { get; set; }
        public float Precio { get; set; }
        public int Alquiler_Id { get; set; }
        public int Equipo_Id { get; set; }
    
        public virtual Alquiler Alquiler { get; set; }
        public virtual Equipo Equipo { get; set; }
    }
}
